export const ADD_ITEM = "ADD_TEM";
export const DEL_ITEM = "DEL_ITEM";

export const ADD_SEARCH_ITEM = "ADD_SEARCH_ITEM";
export const SORT_BY_TITLE_ASC = "SORT_BY_TITLE_ASC";
export const SORT_BY_TITLE_DESC = "SORT_BY_TITLE_DESC";
export const SORT_BY_DATE_ASC = "SORT_BY_DATE_ASC";
export const SORT_BY_DATE_DESC = "SORT_BY_DATE_DESC";
export const SORT_BY_QUALITY_ASC = "SORT_BY_QUALITY_ASC";
export const SORT_BY_QUALITY_DESC = "SORT_BY_QUALITY_DESC";
export const FILTER_EXPLICIT = "FILTER_EXPLICIT";
